use std::error::Error;

pub async fn run() -> Result<(), Box<dyn Error>> {
    Ok(())
}
